# Generated by Django 4.0.1 on 2022-02-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='user_email',
            field=models.CharField(default='admin@gmail.com', max_length=100),
        ),
    ]
